{% set version = "2.0.1" %}

package:
  name: python-lsp-ruff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-lsp-ruff/python-lsp-ruff-{{ version }}.tar.gz
  sha256: b204b4c3016e01a69e9fd6ffbe926ba40b14bc4da57a17c755a381fe14a897d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - lsprotocol >=2022.0.0a1
    - cattrs !=23.2.1
    - python >=3.8
    - python-lsp-server-base
    - ruff >=0.1.5,<0.2.0
    - tomli >=1.1.0

test:
  source_files:
    - tests
  imports:
    - pylsp_ruff
  commands:
    - pip check
    - pytest -vv --cov=pylsp_ruff --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=84
  requires:
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/python-lsp-ruff
  summary: Ruff linting plugin for pylsp
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/python-lsp-ruff

extra:
  recipe-maintainers:
    - bollwyvl
    - jhossbach
    - jonas-w
