{% set version = "2.2.0" %}

package:
  name: python-lsp-ruff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-lsp-ruff/python-lsp-ruff-{{ version }}.tar.gz
  sha256: 67c14067f76bc3d16bd5473a574e0d7b3bd422d723b62d2b2a83356e8af051db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - lsprotocol >=2023.0.1
    - cattrs !=23.2.1
    - python >=3.8
    - python-lsp-server-base
    - ruff >=0.2.0,<0.3.0
    - tomli >=1.1.0

test:
  source_files:
    - tests
  imports:
    - pylsp_ruff
  commands:
    - pip check
    - coverage run --source=pylsp_ruff --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=87
  requires:
    - coverage
    - pip
    - pytest

about:
  home: https://pypi.org/project/python-lsp-ruff
  summary: Ruff linting plugin for pylsp
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/python-lsp-ruff

extra:
  recipe-maintainers:
    - bollwyvl
    - jhossbach
    - jonas-w
