{% set version = "2.2.2" %}

package:
  name: python-lsp-ruff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-lsp-ruff/python_lsp_ruff-{{ version }}.tar.gz
  sha256: 3f80bdb0b4a8ee24624596a1cff60b28cc37771773730f9bf7d946ddff9f0cac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - lsprotocol >=2023.0.1
    - cattrs !=23.2.1
    - python >=3.8
    - python-lsp-server-base
    - ruff >=0.2.0
    - tomli >=1.1.0

test:
  source_files:
    - tests
  imports:
    - pylsp_ruff
  commands:
    - pip check
    - coverage run --source=pylsp_ruff --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=87
  requires:
    - coverage
    - pip
    - pytest

about:
  home: https://pypi.org/project/python-lsp-ruff
  summary: Ruff linting plugin for pylsp
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/python-lsp-ruff

extra:
  recipe-maintainers:
    - bollwyvl
    - jhossbach
    - jonas-w
