{% set version = "1.5.1" %}

package:
  name: python-lsp-ruff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-lsp-ruff/python-lsp-ruff-{{ version }}.tar.gz
  sha256: caf1b8427f5aca6d2b4c300b511c47ad6b4384eee0d9562c23eccb81bf33fa01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - lsprotocol >=2022.0.0a1
    - python >=3.7
    - python-lsp-server-base
    - ruff >=0.0.260
    - tomli >=1.1.0

test:
  source_files:
    - tests
  imports:
    - pylsp_ruff
  commands:
    - pip check
    - pytest -vv --cov=pylsp_ruff --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=84
  requires:
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/python-lsp-ruff
  summary: Ruff linting plugin for pylsp
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-lsp/python-lsp-ruff

extra:
  recipe-maintainers:
    - bollwyvl
    - jhossbach
    - jonas-w
